
try {
    console.log(naoExisto);
} catch(err) {
    console.log('naoExisto n√£o existe.');
    console.log(err);
}
